#!/bin/bash

echo "=== GitHub Authentication Setup ==="
echo ""
echo "GitHub now requires Personal Access Tokens (PAT) instead of passwords."
echo ""
echo "To create a token:"
echo "1. Go to https://github.com/settings/tokens/new"
echo "2. Give it a name like 'Dream Recorder Pi'"
echo "3. Select expiration (recommend 90 days or more)"
echo "4. Select scopes:"
echo "   - repo (all)"
echo "   - workflow (optional, for GitHub Actions)"
echo "5. Click 'Generate token'"
echo "6. Copy the token (you won't see it again!)"
echo ""
echo "Then run these commands:"
echo ""
echo "Option 1 - Store credentials (easier):"
echo "git config credential.helper store"
echo "git push -u origin main"
echo "# Enter username: [YOUR-USERNAME]"
echo "# Enter password: YOUR_TOKEN_HERE"
echo ""
echo "Option 2 - Use SSH (more secure):"
echo "1. Generate SSH key if you don't have one:"
echo "   ssh-keygen -t ed25519 -C '[YOUR-EMAIL]'"
echo "2. Add key to GitHub:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo "   # Copy this and add at https://github.com/settings/keys"
echo "3. Change remote to SSH:"
echo "   git remote set-url origin git@github.com:[YOUR-USERNAME]/dreamrecorder.git"
echo "4. Push:"
echo "   git push -u origin main"
